services:
  ffmpeg-api:
    build: .
    deploy:
      resources:
        limits:
          cpus: '20'
    ports:
      - "8120:8000"
    volumes:
      - ffmpeg_api:/tmp/ffmpeg_api
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=2
      - GUNICORN_TIMEOUT=600
      - FFMPEG_TIMEOUT=0
      - FFMPEG_THREADS=auto
      - KEEP_OUTPUT_FILES=false
      - CELERY_BROKER_URL=redis://ffmpeg-api-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://ffmpeg-api-redis:6379/0
    depends_on:
      - ffmpeg-api-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  ffmpeg-api-worker:
    build: .
    deploy:
      resources:
        limits:
          cpus: '20'
    entrypoint: ["/app/worker-entrypoint.sh"]  # Override entrypoint for worker
    volumes:
      - ffmpeg_api:/tmp/ffmpeg_api
    environment:
      - CELERY_BROKER_URL=redis://ffmpeg-api-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://ffmpeg-api-redis:6379/0
      - FFMPEG_TIMEOUT=0
      - FFMPEG_THREADS=auto
      - KEEP_OUTPUT_FILES=false
      - CELERY_CONCURRENCY=4
    depends_on:
      - ffmpeg-api-redis

  ffmpeg-api-redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  ffmpeg_api:
  redis_data: